/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package connect;

import java.awt.Color;


/**
 *
 * @author s0542624
 */
public class User extends javax.swing.JFrame {
    
    private String startGame = "X";
    private int p1Count = 0;
    private int p2Count = 0;
    private int p3Count = 0;
    
    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        setSize(800, 1000);
        setLocationRelativeTo(null);
    }
    
    private void chooseYourPlayer() {
        if (startGame.equalsIgnoreCase("X")) {
            startGame = "X";
        }
        else if(startGame.equalsIgnoreCase("O")) {
            startGame = "O";
        }
        else if(startGame.equalsIgnoreCase("Y")) {
            startGame = "Y";
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1x1 = new javax.swing.JButton();
        jButton1x2 = new javax.swing.JButton();
        jButton1x3 = new javax.swing.JButton();
        jButton1x4 = new javax.swing.JButton();
        jButton1x5 = new javax.swing.JButton();
        jButton1x6 = new javax.swing.JButton();
        jButton1x7 = new javax.swing.JButton();
        jButton1x8 = new javax.swing.JButton();
        jButton2x1 = new javax.swing.JButton();
        jButton2x2 = new javax.swing.JButton();
        jButton2x3 = new javax.swing.JButton();
        jButton2x4 = new javax.swing.JButton();
        jButton2x5 = new javax.swing.JButton();
        jButton2x6 = new javax.swing.JButton();
        jButton2x7 = new javax.swing.JButton();
        jButton2x8 = new javax.swing.JButton();
        jButton3x1 = new javax.swing.JButton();
        jButton3x2 = new javax.swing.JButton();
        jButton3x3 = new javax.swing.JButton();
        jButton3x4 = new javax.swing.JButton();
        jButton3x5 = new javax.swing.JButton();
        jButton3x6 = new javax.swing.JButton();
        jButton3x7 = new javax.swing.JButton();
        jButton3x8 = new javax.swing.JButton();
        jButton4x1 = new javax.swing.JButton();
        jButton4x2 = new javax.swing.JButton();
        jButton4x3 = new javax.swing.JButton();
        jButton4x4 = new javax.swing.JButton();
        jButton4x5 = new javax.swing.JButton();
        jButton4x6 = new javax.swing.JButton();
        jButton4x7 = new javax.swing.JButton();
        jButton4x8 = new javax.swing.JButton();
        jButton5x1 = new javax.swing.JButton();
        jButton5x2 = new javax.swing.JButton();
        jButton5x3 = new javax.swing.JButton();
        jButton5x4 = new javax.swing.JButton();
        jButton5x5 = new javax.swing.JButton();
        jButton5x6 = new javax.swing.JButton();
        jButton5x7 = new javax.swing.JButton();
        jButton5x8 = new javax.swing.JButton();
        jButton6x1 = new javax.swing.JButton();
        jButton6x2 = new javax.swing.JButton();
        jButton6x3 = new javax.swing.JButton();
        jButton6x4 = new javax.swing.JButton();
        jButton6x5 = new javax.swing.JButton();
        jButton6x6 = new javax.swing.JButton();
        jButton6x7 = new javax.swing.JButton();
        jButton6x8 = new javax.swing.JButton();
        jButton7x1 = new javax.swing.JButton();
        jButton7x2 = new javax.swing.JButton();
        jButton7x3 = new javax.swing.JButton();
        jButton7x4 = new javax.swing.JButton();
        jButton7x5 = new javax.swing.JButton();
        jButton7x6 = new javax.swing.JButton();
        jButton7x7 = new javax.swing.JButton();
        jButton7x8 = new javax.swing.JButton();
        jButton8x1 = new javax.swing.JButton();
        jButton8x2 = new javax.swing.JButton();
        jButton8x3 = new javax.swing.JButton();
        jButton8x4 = new javax.swing.JButton();
        jButton8x5 = new javax.swing.JButton();
        jButton8x6 = new javax.swing.JButton();
        jButton8x7 = new javax.swing.JButton();
        jButton8x8 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(0, 0));

        jPanel1.setLayout(new java.awt.GridLayout(8, 8, 4, 4));

        jButton1x1.setBackground(new java.awt.Color(233, 231, 231));
        jButton1x1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1x1.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton1x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1x1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1x1);

        jButton1x2.setBackground(new java.awt.Color(233, 231, 231));
        jButton1x2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1x2.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton1x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1x2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1x2);

        jButton1x3.setBackground(new java.awt.Color(233, 231, 231));
        jButton1x3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1x3.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton1x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1x3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1x3);

        jButton1x4.setBackground(new java.awt.Color(233, 231, 231));
        jButton1x4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1x4.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton1x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1x4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1x4);

        jButton1x5.setBackground(new java.awt.Color(233, 231, 231));
        jButton1x5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1x5.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton1x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1x5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1x5);

        jButton1x6.setBackground(new java.awt.Color(233, 231, 231));
        jButton1x6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1x6.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton1x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1x6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1x6);

        jButton1x7.setBackground(new java.awt.Color(233, 231, 231));
        jButton1x7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1x7.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton1x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1x7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1x7);

        jButton1x8.setBackground(new java.awt.Color(233, 231, 231));
        jButton1x8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1x8.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton1x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1x8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1x8);

        jButton2x1.setBackground(new java.awt.Color(233, 231, 231));
        jButton2x1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2x1.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton2x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2x1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2x1);

        jButton2x2.setBackground(new java.awt.Color(233, 231, 231));
        jButton2x2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2x2.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton2x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2x2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2x2);

        jButton2x3.setBackground(new java.awt.Color(233, 231, 231));
        jButton2x3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2x3.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton2x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2x3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2x3);

        jButton2x4.setBackground(new java.awt.Color(233, 231, 231));
        jButton2x4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2x4.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton2x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2x4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2x4);

        jButton2x5.setBackground(new java.awt.Color(233, 231, 231));
        jButton2x5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2x5.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton2x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2x5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2x5);

        jButton2x6.setBackground(new java.awt.Color(233, 231, 231));
        jButton2x6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2x6.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton2x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2x6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2x6);

        jButton2x7.setBackground(new java.awt.Color(233, 231, 231));
        jButton2x7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2x7.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton2x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2x7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2x7);

        jButton2x8.setBackground(new java.awt.Color(233, 231, 231));
        jButton2x8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2x8.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton2x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2x8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2x8);

        jButton3x1.setBackground(new java.awt.Color(233, 231, 231));
        jButton3x1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3x1.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton3x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3x1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3x1);

        jButton3x2.setBackground(new java.awt.Color(233, 231, 231));
        jButton3x2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3x2.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton3x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3x2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3x2);

        jButton3x3.setBackground(new java.awt.Color(233, 231, 231));
        jButton3x3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3x3.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton3x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3x3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3x3);

        jButton3x4.setBackground(new java.awt.Color(233, 231, 231));
        jButton3x4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3x4.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton3x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3x4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3x4);

        jButton3x5.setBackground(new java.awt.Color(233, 231, 231));
        jButton3x5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3x5.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton3x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3x5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3x5);

        jButton3x6.setBackground(new java.awt.Color(233, 231, 231));
        jButton3x6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3x6.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton3x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3x6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3x6);

        jButton3x7.setBackground(new java.awt.Color(233, 231, 231));
        jButton3x7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3x7.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton3x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3x7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3x7);

        jButton3x8.setBackground(new java.awt.Color(233, 231, 231));
        jButton3x8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3x8.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton3x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3x8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3x8);

        jButton4x1.setBackground(new java.awt.Color(233, 231, 231));
        jButton4x1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4x1.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton4x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4x1);

        jButton4x2.setBackground(new java.awt.Color(233, 231, 231));
        jButton4x2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4x2.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton4x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4x2);

        jButton4x3.setBackground(new java.awt.Color(233, 231, 231));
        jButton4x3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4x3.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton4x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4x3);

        jButton4x4.setBackground(new java.awt.Color(233, 231, 231));
        jButton4x4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4x4.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton4x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4x4);

        jButton4x5.setBackground(new java.awt.Color(233, 231, 231));
        jButton4x5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4x5.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton4x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4x5);

        jButton4x6.setBackground(new java.awt.Color(233, 231, 231));
        jButton4x6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4x6.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton4x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4x6);

        jButton4x7.setBackground(new java.awt.Color(233, 231, 231));
        jButton4x7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4x7.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton4x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4x7);

        jButton4x8.setBackground(new java.awt.Color(233, 231, 231));
        jButton4x8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4x8.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton4x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4x8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4x8);

        jButton5x1.setBackground(new java.awt.Color(233, 231, 231));
        jButton5x1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5x1.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton5x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5x1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5x1);

        jButton5x2.setBackground(new java.awt.Color(233, 231, 231));
        jButton5x2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5x2.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton5x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5x2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5x2);

        jButton5x3.setBackground(new java.awt.Color(233, 231, 231));
        jButton5x3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5x3.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton5x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5x3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5x3);

        jButton5x4.setBackground(new java.awt.Color(233, 231, 231));
        jButton5x4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5x4.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton5x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5x4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5x4);

        jButton5x5.setBackground(new java.awt.Color(233, 231, 231));
        jButton5x5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5x5.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton5x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5x5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5x5);

        jButton5x6.setBackground(new java.awt.Color(233, 231, 231));
        jButton5x6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5x6.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton5x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5x6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5x6);

        jButton5x7.setBackground(new java.awt.Color(233, 231, 231));
        jButton5x7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5x7.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton5x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5x7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5x7);

        jButton5x8.setBackground(new java.awt.Color(233, 231, 231));
        jButton5x8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5x8.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton5x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5x8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5x8);

        jButton6x1.setBackground(new java.awt.Color(233, 231, 231));
        jButton6x1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6x1.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton6x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6x1);

        jButton6x2.setBackground(new java.awt.Color(233, 231, 231));
        jButton6x2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6x2.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton6x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6x2);

        jButton6x3.setBackground(new java.awt.Color(233, 231, 231));
        jButton6x3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6x3.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton6x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6x3);

        jButton6x4.setBackground(new java.awt.Color(233, 231, 231));
        jButton6x4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6x4.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton6x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6x4);

        jButton6x5.setBackground(new java.awt.Color(233, 231, 231));
        jButton6x5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6x5.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton6x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6x5);

        jButton6x6.setBackground(new java.awt.Color(233, 231, 231));
        jButton6x6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6x6.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton6x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6x6);

        jButton6x7.setBackground(new java.awt.Color(233, 231, 231));
        jButton6x7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6x7.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton6x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6x7);

        jButton6x8.setBackground(new java.awt.Color(233, 231, 231));
        jButton6x8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6x8.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton6x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6x8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6x8);

        jButton7x1.setBackground(new java.awt.Color(233, 231, 231));
        jButton7x1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7x1.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton7x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7x1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7x1);

        jButton7x2.setBackground(new java.awt.Color(233, 231, 231));
        jButton7x2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7x2.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton7x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7x2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7x2);

        jButton7x3.setBackground(new java.awt.Color(233, 231, 231));
        jButton7x3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7x3.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton7x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7x3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7x3);

        jButton7x4.setBackground(new java.awt.Color(233, 231, 231));
        jButton7x4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7x4.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton7x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7x4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7x4);

        jButton7x5.setBackground(new java.awt.Color(233, 231, 231));
        jButton7x5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7x5.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton7x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7x5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7x5);

        jButton7x6.setBackground(new java.awt.Color(233, 231, 231));
        jButton7x6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7x6.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton7x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7x6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7x6);

        jButton7x7.setBackground(new java.awt.Color(233, 231, 231));
        jButton7x7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7x7.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton7x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7x7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7x7);

        jButton7x8.setBackground(new java.awt.Color(233, 231, 231));
        jButton7x8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7x8.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton7x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7x8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7x8);

        jButton8x1.setBackground(new java.awt.Color(233, 231, 231));
        jButton8x1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8x1.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton8x1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8x1);

        jButton8x2.setBackground(new java.awt.Color(233, 231, 231));
        jButton8x2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8x2.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton8x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8x2);

        jButton8x3.setBackground(new java.awt.Color(233, 231, 231));
        jButton8x3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8x3.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton8x3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8x3);

        jButton8x4.setBackground(new java.awt.Color(233, 231, 231));
        jButton8x4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8x4.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton8x4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8x4);

        jButton8x5.setBackground(new java.awt.Color(233, 231, 231));
        jButton8x5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8x5.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton8x5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8x5);

        jButton8x6.setBackground(new java.awt.Color(233, 231, 231));
        jButton8x6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8x6.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton8x6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8x6);

        jButton8x7.setBackground(new java.awt.Color(233, 231, 231));
        jButton8x7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8x7.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton8x7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8x7);

        jButton8x8.setBackground(new java.awt.Color(233, 231, 231));
        jButton8x8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8x8.setPreferredSize(new java.awt.Dimension(75, 60));
        jButton8x8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8x8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8x8);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Player One");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Player Two");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Player Three");

        jButtonReset.setBackground(new java.awt.Color(233, 231, 231));
        jButtonReset.setText("Start a new game");
        jButtonReset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
            .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3x8ActionPerformed
                    if (startGame.equalsIgnoreCase("X")) {
            jButton3x8.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton3x8.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton3x8.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton3x8ActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
    
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButton1x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1x1ActionPerformed
        

        if (startGame.equalsIgnoreCase("X")) {
            jButton1x1.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton1x1.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton1x1.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton1x1ActionPerformed

    private void jButton1x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1x2ActionPerformed

        if (startGame.equalsIgnoreCase("X")) {
            jButton1x2.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton1x2.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton1x2.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton1x2ActionPerformed

    private void jButton1x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1x3ActionPerformed

        if (startGame.equalsIgnoreCase("X")) {
            jButton1x3.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton1x3.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton1x3.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton1x3ActionPerformed

    private void jButton1x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1x4ActionPerformed

        if (startGame.equalsIgnoreCase("X")) {
            jButton1x4.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton1x4.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton1x4.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton1x4ActionPerformed

    private void jButton1x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1x5ActionPerformed

        if (startGame.equalsIgnoreCase("X")) {
            jButton1x5.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton1x5.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton1x5.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton1x5ActionPerformed

    private void jButton1x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1x6ActionPerformed

        if (startGame.equalsIgnoreCase("X")) {
            jButton1x6.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton1x6.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton1x6.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton1x6ActionPerformed

    private void jButton1x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1x7ActionPerformed
        
        if (startGame.equalsIgnoreCase("X")) {
            jButton1x7.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton1x7.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton1x7.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton1x7ActionPerformed

    private void jButton1x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1x8ActionPerformed
                if (startGame.equalsIgnoreCase("X")) {
            jButton1x8.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton1x8.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton1x8.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton1x8ActionPerformed

    private void jButton2x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2x1ActionPerformed
            if (startGame.equalsIgnoreCase("X")) {
            jButton2x1.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton2x1.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton2x1.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton2x1ActionPerformed

    private void jButton2x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2x2ActionPerformed
                if (startGame.equalsIgnoreCase("X")) {
            jButton2x2.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton2x2.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton2x2.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton2x2ActionPerformed

    private void jButton2x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2x3ActionPerformed
                if (startGame.equalsIgnoreCase("X")) {
            jButton2x3.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton2x3.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton2x3.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton2x3ActionPerformed

    private void jButton2x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2x4ActionPerformed
                if (startGame.equalsIgnoreCase("X")) {
            jButton2x4.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton2x4.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton2x4.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton2x4ActionPerformed

    private void jButton2x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2x5ActionPerformed
                if (startGame.equalsIgnoreCase("X")) {
            jButton2x5.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton2x5.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton2x5.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton2x5ActionPerformed

    private void jButton2x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2x6ActionPerformed
                if (startGame.equalsIgnoreCase("X")) {
            jButton2x6.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton2x6.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton2x6.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton2x6ActionPerformed

    private void jButton2x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2x7ActionPerformed
                if (startGame.equalsIgnoreCase("X")) {
            jButton2x7.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton2x7.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton2x7.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton2x7ActionPerformed

    private void jButton2x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2x8ActionPerformed
                if (startGame.equalsIgnoreCase("X")) {
            jButton2x8.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton2x8.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton2x8.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton2x8ActionPerformed

    private void jButton3x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3x1ActionPerformed
                if (startGame.equalsIgnoreCase("X")) {
            jButton3x1.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton3x1.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton3x1.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton3x1ActionPerformed

    private void jButton3x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3x2ActionPerformed
                    if (startGame.equalsIgnoreCase("X")) {
            jButton3x2.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton3x2.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton3x2.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton3x2ActionPerformed

    private void jButton3x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3x3ActionPerformed
                    if (startGame.equalsIgnoreCase("X")) {
            jButton3x3.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton3x3.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton3x3.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton3x3ActionPerformed

    private void jButton3x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3x4ActionPerformed
                    if (startGame.equalsIgnoreCase("X")) {
            jButton3x4.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton3x4.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton3x4.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton3x4ActionPerformed

    private void jButton3x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3x5ActionPerformed
                    if (startGame.equalsIgnoreCase("X")) {
            jButton3x5.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton3x5.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton3x5.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton3x5ActionPerformed

    private void jButton3x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3x6ActionPerformed
                    if (startGame.equalsIgnoreCase("X")) {
            jButton3x6.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton3x6.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton3x6.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton3x6ActionPerformed

    private void jButton3x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3x7ActionPerformed
                    if (startGame.equalsIgnoreCase("X")) {
            jButton3x7.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton3x7.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton3x7.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton3x7ActionPerformed

    private void jButton4x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x1ActionPerformed
                    if (startGame.equalsIgnoreCase("X")) {
            jButton4x1.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton4x1.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton4x1.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton4x1ActionPerformed

    private void jButton4x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x2ActionPerformed
                        if (startGame.equalsIgnoreCase("X")) {
            jButton4x2.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton4x2.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton4x2.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton4x2ActionPerformed

    private void jButton4x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x3ActionPerformed
                        if (startGame.equalsIgnoreCase("X")) {
            jButton4x3.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton4x3.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton4x3.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton4x3ActionPerformed

    private void jButton4x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x4ActionPerformed
                        if (startGame.equalsIgnoreCase("X")) {
            jButton4x4.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton4x4.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton4x4.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton4x4ActionPerformed

    private void jButton4x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x5ActionPerformed
                        if (startGame.equalsIgnoreCase("X")) {
            jButton4x5.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton4x5.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton4x5.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton4x5ActionPerformed

    private void jButton4x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x6ActionPerformed
                        if (startGame.equalsIgnoreCase("X")) {
            jButton4x6.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton4x6.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton4x6.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton4x6ActionPerformed

    private void jButton4x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x7ActionPerformed
                        if (startGame.equalsIgnoreCase("X")) {
            jButton4x7.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton4x7.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton4x7.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton4x7ActionPerformed

    private void jButton4x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4x8ActionPerformed
                        if (startGame.equalsIgnoreCase("X")) {
            jButton4x8.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton4x8.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton4x8.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton4x8ActionPerformed

    private void jButton5x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5x1ActionPerformed
                    if (startGame.equalsIgnoreCase("X")) {
            jButton5x1.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton5x1.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton5x1.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton5x1ActionPerformed

    private void jButton5x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5x2ActionPerformed
                        if (startGame.equalsIgnoreCase("X")) {
            jButton5x2.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton5x2.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton5x2.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton5x2ActionPerformed

    private void jButton5x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5x3ActionPerformed
                            if (startGame.equalsIgnoreCase("X")) {
            jButton5x3.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton5x3.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton5x3.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton5x3ActionPerformed

    private void jButton5x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5x4ActionPerformed
                            if (startGame.equalsIgnoreCase("X")) {
            jButton5x4.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton5x4.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton5x4.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton5x4ActionPerformed

    private void jButton5x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5x5ActionPerformed
                            if (startGame.equalsIgnoreCase("X")) {
            jButton5x5.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton5x5.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton5x5.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton5x5ActionPerformed

    private void jButton5x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5x6ActionPerformed
        if (startGame.equalsIgnoreCase("X")) {
            jButton5x6.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton5x6.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton5x6.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton5x6ActionPerformed

    private void jButton5x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5x7ActionPerformed
        if (startGame.equalsIgnoreCase("X")) {
            jButton5x7.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton5x7.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton5x7.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton5x7ActionPerformed

    private void jButton5x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5x8ActionPerformed
                            if (startGame.equalsIgnoreCase("X")) {
            jButton5x8.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton5x8.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton5x8.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton5x8ActionPerformed

    private void jButton6x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x1ActionPerformed
        if (startGame.equalsIgnoreCase("X")) {
            jButton6x1.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton6x1.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton6x1.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton6x1ActionPerformed

    private void jButton6x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x2ActionPerformed
        if (startGame.equalsIgnoreCase("X")) {
            jButton6x2.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton6x2.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton6x2.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton6x2ActionPerformed

    private void jButton6x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x3ActionPerformed
            if (startGame.equalsIgnoreCase("X")) {
            jButton6x3.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton6x3.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton6x3.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton6x3ActionPerformed

    private void jButton6x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x4ActionPerformed
            if (startGame.equalsIgnoreCase("X")) {
            jButton6x4.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton6x4.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton6x4.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton6x4ActionPerformed

    private void jButton6x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x5ActionPerformed
            if (startGame.equalsIgnoreCase("X")) {
            jButton6x5.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton6x5.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton6x5.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton6x5ActionPerformed

    private void jButton6x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x6ActionPerformed
            if (startGame.equalsIgnoreCase("X")) {
            jButton6x6.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton6x6.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton6x6.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer(); 
    }//GEN-LAST:event_jButton6x6ActionPerformed

    private void jButton6x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x7ActionPerformed
            if (startGame.equalsIgnoreCase("X")) {
            jButton6x7.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton6x7.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton6x7.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton6x7ActionPerformed

    private void jButton6x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6x8ActionPerformed
            if (startGame.equalsIgnoreCase("X")) {
            jButton6x8.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton6x8.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton6x8.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton6x8ActionPerformed

    private void jButton7x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7x1ActionPerformed
            if (startGame.equalsIgnoreCase("X")) {
            jButton7x1.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton7x1.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton7x1.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton7x1ActionPerformed

    private void jButton7x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7x2ActionPerformed
            if (startGame.equalsIgnoreCase("X")) {
            jButton7x2.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton7x2.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton7x2.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton7x2ActionPerformed

    private void jButton7x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7x3ActionPerformed
        if (startGame.equalsIgnoreCase("X")) {
            jButton7x3.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton7x3.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton7x3.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton7x3ActionPerformed

    private void jButton7x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7x4ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton7x4.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton7x4.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton7x4.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton7x4ActionPerformed

    private void jButton7x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7x5ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton7x5.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton7x5.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton7x5.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton7x5ActionPerformed

    private void jButton7x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7x6ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton7x6.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton7x6.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton7x6.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton7x6ActionPerformed

    private void jButton7x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7x7ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton7x7.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton7x7.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton7x7.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton7x7ActionPerformed

    private void jButton7x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7x8ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton7x8.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton7x8.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton7x8.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton7x8ActionPerformed

    private void jButton8x1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x1ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton8x1.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton8x1.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton8x1.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton8x1ActionPerformed

    private void jButton8x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x2ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton8x2.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton8x2.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton8x2.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton8x2ActionPerformed

    private void jButton8x3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x3ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton8x3.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton8x3.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton8x3.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton8x3ActionPerformed

    private void jButton8x4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x4ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton8x4.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton8x4.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton8x4.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton8x4ActionPerformed

    private void jButton8x5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x5ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton8x5.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton8x5.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton8x5.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton8x5ActionPerformed

    private void jButton8x6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x6ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton8x6.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton8x6.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton8x6.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton8x6ActionPerformed

    private void jButton8x7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x7ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton8x7.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton8x7.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton8x7.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton8x7ActionPerformed

    private void jButton8x8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8x8ActionPerformed
    if (startGame.equalsIgnoreCase("X")) {
            jButton8x8.setBackground(Color.blue);
            startGame = "O";
        }
        else if (startGame.equalsIgnoreCase("O")) {
            jButton8x8.setBackground(Color.red);
            startGame = "Y";
        }
        else if (startGame.equalsIgnoreCase("Y")) {
            jButton8x8.setBackground(Color.GREEN);
            startGame = "X";
        }
        
        chooseYourPlayer();
    }//GEN-LAST:event_jButton8x8ActionPerformed
 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1x1;
    private javax.swing.JButton jButton1x2;
    private javax.swing.JButton jButton1x3;
    private javax.swing.JButton jButton1x4;
    private javax.swing.JButton jButton1x5;
    private javax.swing.JButton jButton1x6;
    private javax.swing.JButton jButton1x7;
    private javax.swing.JButton jButton1x8;
    private javax.swing.JButton jButton2x1;
    private javax.swing.JButton jButton2x2;
    private javax.swing.JButton jButton2x3;
    private javax.swing.JButton jButton2x4;
    private javax.swing.JButton jButton2x5;
    private javax.swing.JButton jButton2x6;
    private javax.swing.JButton jButton2x7;
    private javax.swing.JButton jButton2x8;
    private javax.swing.JButton jButton3x1;
    private javax.swing.JButton jButton3x2;
    private javax.swing.JButton jButton3x3;
    private javax.swing.JButton jButton3x4;
    private javax.swing.JButton jButton3x5;
    private javax.swing.JButton jButton3x6;
    private javax.swing.JButton jButton3x7;
    private javax.swing.JButton jButton3x8;
    private javax.swing.JButton jButton4x1;
    private javax.swing.JButton jButton4x2;
    private javax.swing.JButton jButton4x3;
    private javax.swing.JButton jButton4x4;
    private javax.swing.JButton jButton4x5;
    private javax.swing.JButton jButton4x6;
    private javax.swing.JButton jButton4x7;
    private javax.swing.JButton jButton4x8;
    private javax.swing.JButton jButton5x1;
    private javax.swing.JButton jButton5x2;
    private javax.swing.JButton jButton5x3;
    private javax.swing.JButton jButton5x4;
    private javax.swing.JButton jButton5x5;
    private javax.swing.JButton jButton5x6;
    private javax.swing.JButton jButton5x7;
    private javax.swing.JButton jButton5x8;
    private javax.swing.JButton jButton6x1;
    private javax.swing.JButton jButton6x2;
    private javax.swing.JButton jButton6x3;
    private javax.swing.JButton jButton6x4;
    private javax.swing.JButton jButton6x5;
    private javax.swing.JButton jButton6x6;
    private javax.swing.JButton jButton6x7;
    private javax.swing.JButton jButton6x8;
    private javax.swing.JButton jButton7x1;
    private javax.swing.JButton jButton7x2;
    private javax.swing.JButton jButton7x3;
    private javax.swing.JButton jButton7x4;
    private javax.swing.JButton jButton7x5;
    private javax.swing.JButton jButton7x6;
    private javax.swing.JButton jButton7x7;
    private javax.swing.JButton jButton7x8;
    private javax.swing.JButton jButton8x1;
    private javax.swing.JButton jButton8x2;
    private javax.swing.JButton jButton8x3;
    private javax.swing.JButton jButton8x4;
    private javax.swing.JButton jButton8x5;
    private javax.swing.JButton jButton8x6;
    private javax.swing.JButton jButton8x7;
    private javax.swing.JButton jButton8x8;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
